version: '3'
services:
  mysql:
    container_name: demo82-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop_demo82
    networks:
      - prestashop_network
    volumes:
      - demo82dbdata:/var/lib/mysql
  prestashop:
    container_name: demo82
    image: prestashop/prestashop:8.2.0
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 9096:80
    environment:
      DB_SERVER: demo82-mysql
      DB_NAME: prestashop_demo82
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admindemo82
      PS_FOLDER_INSTALL: install1234
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./
        target:  /var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: demo82-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: demo82-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  demo82dbdata:
